---
- hosts: webservers
  become: true
  tasks:
#  - name: Install wget
#    yum: name=wget state=present
#  - name: Download Tomcat
#    get_url: url=https://archive.apache.org/dist/tomcat/tomcat-7/v7.0.109/bin/apache-tomcat-7.0.109.tar.gz dest=/home/ansible/
#  - name: Extract the file downloaded tomcat file
#    command: tar -xvf apache-tomcat-7.0.109.tar.gz
#  - name: Move the Tomcat directory to a smaller one
#    command: mv apache-tomcat-7.0.109 tomcat
#  - name: Create user tomcat
#   command: useradd tomcat
#  - name: Change Ownership and group of the Tomcat directory
#    file: path=/home/ansible/tomcat owner=ansible group=ansible mode=775 state=directory
#     recurse=yes
  - name: Start Tomcat
    command: nohup /home/ansible/tomcat/bin/startup.sh
#  - name: Configuration file changes
#    copy: src=/home/ansible/tomcat-users.xml.j2 dest=/home/ansible/tomcat/conf/tomcat-users.xml
#  - name: Configuration file server.xml changes
#    lineinfile:
#      path: /home/ansible/tomcat/conf/server.xml
#      regexp: '<Connector port="8080" protocol="HTTP/1.1"'
#     line: '<Connector port="8088" protocol="HTTP/1.1"'
#     template: src=/home/ansible/server.xml.j2 dest=/home/ansible/tomcat/conf/server.xml
# - name: Configuration file changes
#    copy: src=/home/ansible/context.xml.j2 dest=/home/ansible/tomcat/webapps/manager/META-INF/context.xml
#     become: true
    become_user: ansible
